name: pullll-github-action-custom

on:
  ['push']

jobs:
  my-custom:
    runs-on: ubuntu-latest
    name: hello 드가자
    steps:
      - name: hello step임
        id: hello
        uses: dkkfjvv/barsson@0.0.3
        with:
          who-to-greet: "what the heck12"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.outputKey1 }}"
